### ISSUE TITLE
Definition causes type to be defined twice - compilation error

### ISSUE THREAD

**Issue by okthatsneat** [zalando/play-swagger#50]
errror:
```

play.sbt.PlayExceptions$CompilationException: Compilation error[ErrorSource is already defined as type ErrorSource]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:27) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:49) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$taskFailureHandler$1.apply(PlayReload.scala:44) ~[na:na]
	at scala.Option.map(Option.scala:145) ~[scala-library-2.11.7.jar:na]
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:44) ~[na:na]
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:40) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
	at play.sbt.run.PlayReload$$anonfun$compile$1.apply(PlayReload.scala:17) ~[na:na]
```

the definitions that likely cause this: 
```yaml
  Links:
    type: object
    description: Links response
    properties:
      self:
        description: The link that generated the current response document
        type: string
      related:
        description: A related resource link when the primary data represents a resource relationship
        type: string

  Meta:
    type: object
    description: Meta
    properties:
      copyright:
        description: Zalando SE Copyright notice
        type: string

  ErrorSource:
    type: object
    description: Indicate the source of error
    properties:
      pointer:
        description: A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].
        type: string
      parameter:
        description: A string indicating which URI query parameter caused the error.
        type: string

  Error:
    type: object
    description: Error object
    properties:
      status:
       description: The HTTP status code applicable to this p roblem, expressed as a string value.
       type: string
      code:
       description: An application-specific error code, expressed as a string value.
       type: string
      title:
       description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrenc of the problem, except for purposes of localization.
       type: string
      detail:
       description: A human-readable explanation specific to this occurrence of the problem.
       type: string
      source:
       description: An object containing references to the source of the error
       $ref: '#/definitions/ErrorSource'

  Errors:
    type: object
    description: Array of error objects
    properties:
      errors:
        description: All errors
        type: array
        items:
          $ref: '#/definitions/Error'
```

the generated file that's causing the compilation error: 
```scala
package echo
package object yaml {
import java.util.Date
import java.io.File


    type MetaCopyright = Option[String]

    type ErrorsErrorsOpt = scala.collection.Seq[Error]

    type ModelSchemaSpecialDescriptions = Option[ModelSchemaAgeGroups]

    type ModelSchemaRootLinks = Option[Links]

    type ErrorSource = Option[ErrorSource]

    type ModelSchemaAgeGroups = scala.collection.Seq[String]

    type ModelSchemaRootData = Option[ModelSchema]

    type ErrorsErrors = Option[ErrorsErrorsOpt]

    type ModelSchemaRootMeta = Option[Meta]

    case class ModelSchemaRoot(data: ModelSchemaRootData, 
meta: ModelSchemaRootMeta, 
links: ModelSchemaRootLinks
) 

    case class Errors(errors: ErrorsErrors
) 

    case class ErrorSource(pointer: MetaCopyright, 
parameter: MetaCopyright
) 

    case class Meta(copyright: MetaCopyright
) 

    case class ModelSchema(name: String, 
sizeRegister: String, 
brand: String, 
partnerArticleModelId: Int, 
silhouetteId: String, 
description: MetaCopyright, 
ageGroups: ModelSchemaAgeGroups, 
keywords: MetaCopyright, 
lengthRegister: MetaCopyright, 
specialDescriptions: ModelSchemaSpecialDescriptions, 
articleModelAttributes: ModelSchemaSpecialDescriptions
) 

    case class Error(source: ErrorSource, 
code: MetaCopyright, 
status: MetaCopyright, 
detail: MetaCopyright, 
title: MetaCopyright
) 

    case class Links(self: MetaCopyright, 
related: MetaCopyright
) 

    


    type SchemaModelGetResponses200 = Option[ModelSchemaRoot]

    

}
```

**Comment by slavaschmidt** [comment]
Could you please provide the whole specification?

**Comment by okthatsneat** [comment]
sure thing 
```yaml
swagger: '2.0'
info:
  version: 0.0.1_Hackweek4
  title: ArticleValidator
  description: |
    Validates article data against the Zalando Shop schema
schemes:
  - http
host: localhost:9000
paths:
  /schema/model:
    get:
      responses:
        200:
          description: |
            Schema representing sales channel and merchant
            specific structure and valid values for models to create articles with.
          schema:
            $ref: "#/definitions/ModelSchemaRoot"

definitions:

  ModelSchemaRoot:
    type: object
    description: Representation of a schema for a model
    properties:
      data:
        description: The schema object
        $ref: '#/definitions/ModelSchema'
      meta:
        description: Meta object
        $ref: '#/definitions/Meta'
      links:
        description: Links
        $ref: '#/definitions/Links'

  ModelSchema:
    type: object
    description: Schema
    required:
      - partnerArticleModelId
      - silhouetteId
      - name
      - brand
      - ageGroups
      - sizeRegister
    properties:

      # --- Required properties ------------------------------------------------------------------->

      partnerArticleModelId:
        description: ???
        type: integer
        format: ???
      silhouetteId:
        type: string
        enum:
          - ankle_boots
          - backless_slipper
          - backpack
          - bag
          - ball
          - ballerina_shoe
          - bathrobe
          - bathroom
          - beach_accessoires
          - beach_shirt
          - beach_trouser
          - beauty_equipment
          - bedroom
          - belt
          - bicycle
          - bicycle_equipment
          - bikini_combination
          - bikini_top
          - boards
          - boots
          - bra
          - bustier
          - cardigan
          - case
          - cleansing
          - coat
          - combination_clothing
          - corsage
          - dress
          - etui
          - eye_cosmetic
          - face_cosmetic
          - first_shoe
          - fitness
          - fragrance
          - glasses
          - gloves
          - hair
          - headgear
          - headphones
          - jacket
          - jewellery
          - keychain
          - kitchen
          - lip_cosmetic
          - living
          - lounge
          - low_shoe
          - nail
          - night_shirt
          - night_trouser
          - nightdress
          - nightwear_combination
          - one_piece_beachwear
          - one_piece_nightwear
          - one_piece_suit
          - one_piece_underwear
          - other_accessoires
          - other_equipment
          - peeling
          - protector
          - pullover
          - pumps
          - racket
          - sandals
          - scarf
          - shave
          - shirt
          - shoe_accessoires
          - skates
          - ski
          - skincare
          - skirt
          - sleeping_bag
          - sneaker
          - stocking
          - suit_accessoires
          - sun
          - system
          - t_shirt_top
          - tent
          - tights
          - toys
          - travel_equipment
          - trouser
          - umbrella
          - underpant
          - undershirt
          - underwear_combination
          - vest
          - voucher
          - wallet
          - watch
      name:
        type: string
        description: Product name
      brand:
        description: Zalando brand code
        type: string
        minLength: 3
        maxLength: 3
        pattern: /[A-Z0-9]{3,3}/
      ageGroups:
        type: array
        items:
          type: string
          enum:
            - baby
            - kid
            - teen
            - adult
        maxItems: 4
      sizeRegister:
        type: string
        pattern: /[1-9][A-Z0-9]*/
        minLength: 10
        maxLength: 10

      # --- Optional properties ------------------------------------------------------------------->

      articleModelAttributes:
        description: |
          Optional collection of product attributes - if present at least one attribute is required
        type: array
        minItems: 1
        items:
          type: string
      lengthRegister:
        description: Zalando Product Length Grid
        type: string
        pattern: /[1-9][A-Z0-9]*/
        minLength: 10
        maxLength: 10
      keywords:
        description: |
          Product Keywords. Comma-Space (', ') separated Keyword List. A keyword may contain letters
          both upper and lowercase as well as numbers and spaces. Each keyword has a maximum length of 255 characters.
        type: string
        pattern: /([\w\s]{1,255}|([\w\s]{1,255}, )+[\w\s]{1,255})/
      description:
        type: string
      specialDescriptions:
        type: array
        items:
          description: |
            Each
            occurance of the
            'specialDescription'
            node will be
            transformed
            into a
            single line in the
            Zalando Shop Frontend
          type: string

  Links:
    type: object
    description: Links response
    properties:
      self:
        description: The link that generated the current response document
        type: string
      related:
        description: A related resource link when the primary data represents a resource relationship
        type: string

  Meta:
    type: object
    description: Meta
    properties:
      copyright:
        description: Zalando SE Copyright notice
        type: string

  # ErrorSource:
  #   type: object
  #   description: Indicate the source of error
  #   properties:
  #     pointer:
  #       description: A JSON Pointer [RFC6901] to the associated entity in the request document [e.g. "/data" for a primary data object, or "/data/attributes/title" for a specific attribute].
  #       type: string
  #     parameter:
  #       description: A string indicating which URI query parameter caused the error.
  #       type: string

  # Error:
  #   type: object
  #   description: Error object
  #   properties:
  #     status:
  #      description: The HTTP status code applicable to this p roblem, expressed as a string value.
  #      type: string
  #     code:
  #      description: An application-specific error code, expressed as a string value.
  #      type: string
  #     title:
  #      description: A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrenc of the problem, except for purposes of localization.
  #      type: string
  #     detail:
  #      description: A human-readable explanation specific to this occurrence of the problem.
  #      type: string
  #     source:
  #      description: An object containing references to the source of the error
  #      $ref: '#/definitions/ErrorSource'

  # Errors:
  #   type: object
  #   description: Array of error objects
  #   properties:
  #     errors:
  #       description: All errors
  #       type: array
  #       items:
  #         $ref: '#/definitions/Error'


```

**Comment by slavaschmidt** [comment]
Fixed in v.0.1.4
