### ISSUE TITLE
Error injecting constructor, scala.NotImplementedError: an implementation is missing

### ISSUE THREAD

**Issue by okthatsneat** [zalando/play-swagger#54]
steps to reproduce: 
* replace yaml file with this: 
```yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Echo
  description: |
    Echoes back every URL, method, parameter and header
    Feel free to make a path or an operation and use _Try Operation_ to test it. The echo server will
    render back everything.
schemes:
  - http
host: localhost:9000
basePath: /echo
paths:
  /:
    get:
      responses:
        200:
          description: Echo GET
          schema:
            type: string

    post:
      responses:
        200:
          description: Echo POST
          schema:
            type: object
            properties:
              name:
                type: string
              year:
                type: string
      parameters:
        - name: name
          in: query
          description: name
          type: string
        - name: year
          in: query
          description: year
          type: string
  /test-path/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: ID
          type: string
          required: true
      responses:
        200:
          description: Echo test-path
          schema:
            type: string
  /schema/model:
    get:
      responses:
        200:
          description: |
            Schema representing sales channel and merchant
            specific structure and valid values for models to create articles with.
          schema:
            $ref: "#/definitions/ModelSchema"

definitions:

  ModelSchema:
    type: object
    description: Schema
    required:
      - partnerArticleModelId
      - silhouetteId
      - name
      - brand
      - sizeRegister
    properties:

      # --- Required properties ------------------------------------------------------------------->

      partnerArticleModelId:
        description: ???
        type: integer
        format: ???
      silhouetteId:
        type: string
        enum:
          - ankle_boots
          - backless_slipper
          - backpack
          - bag
          - ball
          - ballerina_shoe
          - bathrobe
          - bathroom
          - beach_accessoires
          - beach_shirt
          - beach_trouser
          - beauty_equipment
          - bedroom
          - belt
          - bicycle
          - bicycle_equipment
          - bikini_combination
          - bikini_top
          - boards
          - boots
          - bra
          - bustier
          - cardigan
          - case
          - cleansing
          - coat
          - combination_clothing
          - corsage
          - dress
          - etui
          - eye_cosmetic
          - face_cosmetic
          - first_shoe
          - fitness
          - fragrance
          - glasses
          - gloves
          - hair
          - headgear
          - headphones
          - jacket
          - jewellery
          - keychain
          - kitchen
          - lip_cosmetic
          - living
          - lounge
          - low_shoe
          - nail
          - night_shirt
          - night_trouser
          - nightdress
          - nightwear_combination
          - one_piece_beachwear
          - one_piece_nightwear
          - one_piece_suit
          - one_piece_underwear
          - other_accessoires
          - other_equipment
          - peeling
          - protector
          - pullover
          - pumps
          - racket
          - sandals
          - scarf
          - shave
          - shirt
          - shoe_accessoires
          - skates
          - ski
          - skincare
          - skirt
          - sleeping_bag
          - sneaker
          - stocking
          - suit_accessoires
          - sun
          - system
          - t_shirt_top
          - tent
          - tights
          - toys
          - travel_equipment
          - trouser
          - umbrella
          - underpant
          - undershirt
          - underwear_combination
          - vest
          - voucher
          - wallet
          - watch
      name:
        type: string
        description: Product name
      brand:
        description: Zalando brand code
        type: string
        minLength: 3
        maxLength: 3
      sizeRegister:
        type: string
        minLength: 10
        maxLength: 10

      # --- Optional properties ------------------------------------------------------------------->

      lengthRegister:
        description: Zalando Product Length Grid
        type: string
        minLength: 10
        maxLength: 10
      keywords:
        description: |
          Product Keywords. Comma-Space (', ') separated Keyword List. A keyword may contain letters
          both upper and lowercase as well as numbers and spaces. Each keyword has a maximum length of 255 characters.
        type: string
      description:
        type: string
```

expected: swagger ui rendering 

got instead: 

```bash
[error] - application -

! @6oej56a7i - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, scala.NotImplementedError: an implementation is missing
  at echo.yaml.EchoYaml.<init>(echo.yaml.scala:17)
  while locating echo.yaml.EchoYaml
    for parameter 1 at echo.yaml.Routes.<init>(Routes.scala:28)
  while locating echo.yaml.Routes
    for parameter 3 at router.Routes.<init>(Routes.scala:35)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:165) ~[play-server_2.11-2.4.3.jar:2.4.3]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.3.jar:2.4.3]
	at scala.Option.map(Option.scala:146) ~[scala-library-2.11.7.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.3.jar:2.4.3]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.3.jar:2.4.3]
	at scala.util.Success.flatMap(Try.scala:231) ~[scala-library-2.11.7.jar:na]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.3.jar:2.4.3]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1.apply(DevServerStart.scala:111) ~[play-server_2.11-2.4.3.jar:2.4.3]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[scala-library-2.11.7.jar:na]
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40) ~[akka-actor_2.11-2.3.13.jar:na]
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) ~[akka-actor_2.11-2.3.13.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.11.7.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[scala-library-2.11.7.jar:na]
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, scala.NotImplementedError: an implementation is missing
  at echo.yaml.EchoYaml.<init>(echo.yaml.scala:17)
  while locating echo.yaml.EchoYaml
    for parameter 1 at echo.yaml.Routes.<init>(Routes.scala:28)
  while locating echo.yaml.Routes
    for parameter 3 at router.Routes.<init>(Routes.scala:35)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1025) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:316) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Application$class.routes(Application.scala:111) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.DefaultApplication.routes(Application.scala:240) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:90) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:87) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Play$$anonfun$start$1.apply(Play.scala:87) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.Play$.start(Play.scala:87) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:156) ~[play-server_2.11-2.4.3.jar:2.4.3]
	... 15 common frames omitted
Caused by: scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225) ~[scala-library-2.11.7.jar:na]
	at echo.yaml.EchoYaml.<init>(echo.yaml.scala:35) ~[na:na]
	at echo.yaml.EchoYaml$$FastClassByGuice$$d9dc25ea.newInstance(<generated>) ~[na:na]
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40) ~[guice-4.0.jar:na]
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:61) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:105) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38) ~[guice-4.0.jar:na]
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:104) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:267) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1103) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1051) ~[guice-4.0.jar:na]
	at play.api.inject.guice.GuiceInjector.instanceOf(GuiceInjectorBuilder.scala:321) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.RoutesProvider$$anonfun$2.apply(BuiltinModule.scala:67) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.RoutesProvider$$anonfun$2.apply(BuiltinModule.scala:67) ~[play_2.11-2.4.3.jar:2.4.3]
	at scala.Option.fold(Option.scala:158) ~[scala-library-2.11.7.jar:na]
	at play.api.inject.RoutesProvider.get$lzycompute(BuiltinModule.scala:67) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:63) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.inject.RoutesProvider.get(BuiltinModule.scala:62) ~[play_2.11-2.4.3.jar:2.4.3]
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81) ~[guice-4.0.jar:na]
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:72) ~[guice-4.0.jar:na]
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:61) ~[guice-4.0.jar:na]
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:62) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java:1016) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1092) ~[guice-4.0.jar:na]
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1012) ~[guice-4.0.jar:na]
	... 26 common frames omitted
```

**Comment by okthatsneat** [comment]
I might add that this is attempting to strip the parts of the yaml that caused issues

**Comment by okthatsneat** [comment]
was able to reproduce the behavior after ctrl-d , ```sbt clean``` , activator run tho.

**Comment by slavaschmidt** [comment]
I assume you have something like ```???```in your controller? Somewhere near line 35 in file ```echo.yaml.scala```
This code is generated if new API call was added to the specification. Please implement this method in order to get rid of the error.

**Comment by okthatsneat** [comment]
Indeed: 
```scala
    val getSchemaModel = getSchemaModelAction {
                                                                                                            ???
            
        } //////// EOF ////////  getSchemaModelAction
    }
}

```
was generated; I just missed the ??? as it was way over on the right side ( you already mentioned the new template engine will solve this ) and was still confused about what's generated and what's not. 

thank you!
-p
